[tools]
# Required for mise completions
usage = "latest"

neovim = "stable"
opencode = "latest"

terraform = "1"
terragrunt = "latest"
tflint = "latest"
trivy = "latest"

kind = "0.22.0"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
helm = "3"

rust = "1"
golang = "1"
nodejs = "24"

pnpm = "latest"
uv = "latest"

jq = "latest"
yq = "latest"

pre-commit = "4"
gh = "2"
gum = "0.17.0"
difftastic = "latest"
